schedules:
- cron: "0 6 * * *"   
  displayName: Daily 6AM build
  branches:
    include:
    - main
  always: true


pool:
  vmImage: ubuntu-latest


jobs:
- job: DownloadAndExtract
  steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: add IP to firewall
    inputs:
      azureSubscription: 'test-deploy-legacy'
      ScriptType: 'InlineScript'
      Inline: |
        $IP= Invoke-RestMethod http://ipinfo.io/json | Select -exp ip     
        $IP
        Add-AzStorageAccountNetworkRule -ResourceGroupName "adb-test-mapserver-rg" -AccountName "$(storageAccountName)" -IPAddressOrRange "$IP"
      preferredAzurePowerShellVersion: '3.1.0'

  - script: |
      wget "https://kart.artsdatabanken.no/WMS/kartdata/artskart/artskart.zip"
      unzip artskart.zip -d extracted
    displayName: 'Download and Extract Artskart Data'
  

  - task: AzureCLI@2
    displayName: "Upload files to Azure File Share"
    inputs:
      azureSubscription: 'test-deploy-legacy'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Uploading files from: $(Build.SourcesDirectory)"
        az storage file upload-batch \
         --account-name $(storageAccountName) \
         --account-key $(storageAccountKey) \
          --source "$(Build.SourcesDirectory)/extracted/artskartredOO.sqlite" \
          --destination "mapserverdata/test"

  - task: AzurePowerShell@5
    displayName: remove IP from firewall
    inputs:
      azureSubscription: 'test-deploy-legacy'
      ScriptType: 'InlineScript'
      Inline: |
        $IP= Invoke-RestMethod http://ipinfo.io/json | Select -exp ip  
        $IP  
        Remove-AzStorageAccountNetworkRule -ResourceGroupName "adb-test-mapserver-rg" -AccountName "$(storageAccountName)" -IPAddressOrRange "$IP"
      preferredAzurePowerShellVersion: '3.1.0'